// Copyright 2023 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS
#define COMBO_TERM 200
#define SPECULATIVE_HOLD
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP22
#define I2C1_SCL_PIN GP23

#define AUDIO_PIN GP28
#define AUDIO_PWM_DRIVER PWMD6
#define AUDIO_INIT_DELAY
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A
#define STARTUP_SONG SONG(ODE_TO_JOY)

#define ANALOG_JOYSTICK_Y_AXIS_PIN GP26
#define ANALOG_JOYSTICK_X_AXIS_PIN GP27
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_INVERT_X

#define MY_TAPS
#define BASIC_BANKARU
//#define VIM_MOTIONS
// #define RGB_MATRIX_DISABLE_ALL_EFFECTS

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_KEYRELEASES
#define RGB_MATRIX_KEYREACTIVE_ENABLED
#define SPLIT_TRANSPORT_MIRROR
//#define SPLIT_SHARED_MEMORY_ENABLE
//#define SPLIT_LED_STATE_ENABLE
//#define SPLIT_TRANSPORT_SYNC
