#include "action.h"
#include "keycodes.h"
#include "process_key_override.h"
#include "process_combo.h"
#include "song_list.h"
#include "timer.h"
//#include "rgb_matrix_user.inc"
#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

//RGB

  void keyboard_post_init_user(void) {
 //     //rgb_matrix_disable();
 //     //rgb_matrix_disable_noeeprom();
 //     //rgb_matrix_enable();
 //
      rgb_matrix_mode(RGB_MATRIX_CUSTOM_my_cool_effect);
 //     xprint("TRULY DID MY POST INIT FUNCTION");
  }

// rgb_matrix_effect_t rgb_matrix_effects[] = {
//     RGB_MATRIX_EFFECT(my_cool_effect),
// }

#ifdef AUDIO_ENABLE
float tone_enter[][2] = SONG(GOODBYE_SOUND);

float tone_fail[][2]  = SONG(MUSIC_OFF_SOUND);
float tone_exit[][2]  = SONG(MUSIC_ON_SOUND);
#endif
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define MY_SYM LT(_SYM, KC_NO)
#define MY_NORM LT(_NORM, KC_NO)

#define MY_VIS LT(_NVSY, KC_NO)
#define MY_SHFT MT(MOD_LSFT, KC_CAPS)
#define VI_INS TO(_ENTER)

enum layers {
    _ENTER,
    _SYM,
    _NORM,
    _VIS,
    _SYST,
};

enum custom_keycodes {
    MY_SYST = SAFE_RANGE,
    A_INPUT,
    MY_COPY,
    MY_CUT,
    MY_PASTE,
};

layer_state_t layer_state_set_user(layer_state_t state) {
    if (layer_state_cmp(state, _SYM)) {
        if (!host_keyboard_led_state().num_lock) {
            tap_code(KC_NUM);
        }
    }
    return state;
}

const uint16_t PROGMEM sym_space_combo[] = {MY_SYM, KC_SPC, COMBO_END};
const uint16_t PROGMEM nav_space_combo[] = {MY_NORM, KC_SPC, COMBO_END};

combo_t key_combos[] = {
    COMBO(sym_space_combo, KC_UNDS),
    COMBO(nav_space_combo, KC_TAB),
};


const key_override_t shift_0 = ko_make_basic(MOD_MASK_SHIFT, KC_0, KC_KP_0);
const key_override_t shift_1 = ko_make_basic(MOD_MASK_SHIFT, KC_1, KC_KP_1);
const key_override_t shift_2 = ko_make_basic(MOD_MASK_SHIFT, KC_2, KC_KP_2);
const key_override_t shift_3 = ko_make_basic(MOD_MASK_SHIFT, KC_3, KC_KP_3);
const key_override_t shift_4 = ko_make_basic(MOD_MASK_SHIFT, KC_4, KC_KP_4);
const key_override_t shift_5 = ko_make_basic(MOD_MASK_SHIFT, KC_5, KC_KP_5);
const key_override_t shift_6 = ko_make_basic(MOD_MASK_SHIFT, KC_6, KC_KP_6);
const key_override_t shift_7 = ko_make_basic(MOD_MASK_SHIFT, KC_7, KC_KP_7);
const key_override_t shift_8 = ko_make_basic(MOD_MASK_SHIFT, KC_8, KC_KP_8);
const key_override_t shift_9 = ko_make_basic(MOD_MASK_SHIFT, KC_9, KC_KP_9);

const key_override_t shift_bspc = ko_make_basic(MOD_MASK_SHIFT, KC_BSPC, KC_DEL);


const key_override_t* key_overrides[] = {
    &shift_0,
    &shift_1,
    &shift_2,
    &shift_3,
    &shift_4,
    &shift_5,
    &shift_6,
    &shift_7,
    &shift_8,
    &shift_9,
    &shift_bspc,
    NULL
};

static layer_state_t saved_layer_state;
static bool is_active = false;
static bool other_key_pressed = false;
static uint16_t press_timer;
static keypos_t reset_key_pos;

static uint16_t copy_timer;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {

    // if (!record->event.pressed) {
    //     return true;
    // }

    // Detect other keys while the reset key is physically held
    if (is_active &&
        !(record->event.key.row == reset_key_pos.row &&
          record->event.key.col == reset_key_pos.col) &&

        record->event.pressed) {
        if (!other_key_pressed) {
            other_key_pressed = true;
            layer_clear();
        }
    }

    switch (keycode) {
        case A_INPUT: {
             if (record->event.pressed) {
                 tap_code(KC_RIGHT);
                layer_on(_ENTER);
             }

             //MY_ESC
            // if (record->event.pressed) {
            //     saved_layer_state = layer_state;
            //     reset_key_pos = record->event.key;
            //     is_active = true;
            //     other_key_pressed = false;
            //     press_timer = timer_read();
            // }
            return false;
        }

        case MY_SYM: {
            if (record->tap.count && record->event.pressed){
                layer_invert(_SYM);
                return false;
            }
            return true;
        }

        case MY_NORM: {
            if (record->tap.count && record->event.pressed){
                layer_invert(_NORM);
                return false;
            }
            return true;
        }

        case MY_VIS: {
            if (record->tap.count && record->event.pressed){
                layer_off(_NORM);
                layer_on(_SYM);
                return false;
            }
            return true;
        }

        case MY_COPY: {
            if (record->event.pressed){
                copy_timer = timer_read();
            } else {
                if (timer_elapsed(copy_timer) < TAPPING_TERM) {
                     tap_code16(LCTL(KC_C));
                 } else {
                     tap_code16(LCTL(LSFT(KC_C)));
                }
            }
            return false;
        }

        case MY_CUT: {
            if (record->event.pressed){
                copy_timer = timer_read();
            } else {
                if (timer_elapsed(copy_timer) < TAPPING_TERM) {
                     tap_code16(LCTL(KC_X));
                 } else {
                     tap_code16(LCTL(LSFT(KC_X)));
                }
            }
            return false;
        }

        case MY_PASTE: {
            if (record->event.pressed){
                copy_timer = timer_read();
            } else {
                if (timer_elapsed(copy_timer) < TAPPING_TERM) {
                     tap_code16(LCTL(KC_V));
                 } else {
                     tap_code16(LCTL(LSFT(KC_V)));
                }
            }
            return false;
        }

        case MY_SYST: {
            if (record->event.pressed){
                if ((get_mods() & MOD_MASK_CTRL) &&
                    (get_mods() & MOD_MASK_ALT)) {
                    if (!layer_state_is(_SYST)) {
                        layer_on(_SYST);
#ifdef AUDIO_ENABLE
                        PLAY_SONG(tone_enter);
#endif
                    } else {
                        layer_off(_SYST);
#ifdef AUDIO_ENABLE
                        PLAY_SONG(tone_exit);
#endif
                    }
                }
                else {
#ifdef AUDIO_ENABLE
                PLAY_SONG(tone_fail);
#endif
                }
            return false;
            }
        return true;
        }

    }
    return true;
}


void matrix_scan_user(void) {
    if (is_active) {
        if (!matrix_is_on(reset_key_pos.row, reset_key_pos.col)) {
            // Physical release detected
            is_active = false;

            if (!other_key_pressed &&
                timer_elapsed(press_timer) < TAPPING_TERM) {
                // TAP
                layer_clear();
            } else if (other_key_pressed) {
                // MOD USE
                layer_state = saved_layer_state;
            }
        }
    }
}
// Make holding space do a shift? Or a sym?  Or is that just sloppy?
// It feels like angle brackets should be on the sym level...
// It also feels like semicolon should be on both sym and regular level, but i'm not sure.

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_ENTER] = LAYOUT_split_3x6_3(
        // |........|........|........|........|........|........|........|........|........|........|........|........|........|
            KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,             KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC,
            TO(_NORM),  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,          KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
            MY_NORM,  KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,            KC_N,    KC_M,    KC_COMM, KC_DOT,   KC_SLSH, KC_ENT,
                                       KC_LCTL, KC_LGUI, MY_SHFT,          KC_SPC,  MY_SYM,  KC_LALT),
    [_SYM] = LAYOUT_split_3x6_3(
        // |........|........|........|........|........|........|........|........|........|........|........|........|........|
            _______, KC_RCBR, KC_RBRC, KC_RPRN, KC_PIPE, KC_PERC,          KC_CIRC, KC_AMPR, KC_LPRN, KC_LBRC, KC_LCBR, _______,
            TO(_NORM), KC_1,    KC_2,    KC_3,    KC_4,    KC_5,             KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    _______,
            _______, KC_ASTR, KC_HASH, KC_DLR,  KC_PLUS, KC_EXLM,          KC_EQL,  KC_MINS, _______, _______, _______, _______,
                                       _______, _______, _______,          _______, _______,  _______),
    [_NORM] = LAYOUT_split_3x6_3(
        // |........|........|........|........|........|........|........|........|........|........|........|........|........|
            _______, KC_F1,   VI_WRD,  VI_END,  V_REPL,  KC_F5,            VI_YANK,  VI_UNDO,  KC_UP,   VI_OPEN, VI_PSTE,  _______,
            KC_ESC, KC_F6,    VI_SUB,  VI_DEL,  VI_TIL, A_INPUT,           VI_INS, KC_LEFT, KC_DOWN, KC_RGHT, KC_SCRL, KC_PSCR, //Some macro here?  Scroll Lock?
             _______, KC_AT,   VI_CHG,  VI_X,   VI_VIS, KC_NUM,           VI_PRVW, KC_BSLS, KC_TILD, VI_REPT, VI_SRCH, _______,
                                       _______, _______, _______,          _______, MY_VIS, _______),
    [_NAV] = LAYOUT_split_3x6_3(
        // |........|........|........|........|........|........|........|........|........|........|........|........|........|
            _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,            KC_F11,  KC_F12,  KC_UP,   KC_GRV, KC_PAUS,  _______,
            KC_ESC, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,           KC_INS,  KC_LEFT, KC_DOWN, KC_RGHT, KC_SCRL, KC_PSCR, //Some macro here?  Scroll Lock?
            _______, KC_AT,   MY_CUT,  MY_COPY, MY_PASTE,KC_NUM,           KC_LSCR, KC_BSLS, KC_TILD, KC_MENU, MY_SYST, _______,
                                       _______, _______, _______,          _______, MY_VIS, _______), [_VIS] = LAYOUT_split_3x6_3(
        // |........|........|........|........|........|........|........|........|........|........|........|........|........|
            _______, _______, _______, _______, _______, _______,          _______, _______, KC_PGUP, _______, _______, _______,
            MY_ESC, _______, XXXXXXX, _______, _______, _______,          _______, KC_HOME, KC_PGDN, KC_END,  _______, _______,
            _______, _______, _______, _______, _______, _______,          _______, _______, _______, _______, _______, _______,
                                       _______, _______, _______,          _______, _______,  _______),
    [_SYST] = LAYOUT_split_3x6_3(
        // |........|........|........|........|........|........|........|........|........|........|........|........|........|
            QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, QK_MAKE,          DB_TOGG, QK_RBT,  XXXXXXX, XXXXXXX, XXXXXXX, _______,
            A_INPUT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          EE_CLR,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
            RM_VALU, RM_HUEU, RM_SATU, RM_NEXT, RM_TOGG, XXXXXXX,          RM_VALD, RM_HUED, RM_SATD, RM_PREV, CK_TOGG, _______,
                                       _______, _______, MY_ESC,          _______, _______, _______)
};


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


