POINTING_DEVICE_DRIVER = analog_joystick
POINTING_DEVICE_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
AUDIO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
SRC += lib/oled.c
CONSOLE_ENABLE = yes

