#include "keycodes.h"
#include "keymap_us.h"
#include "process_key_override.h"
#include "process_combo.h"
#include "song_list.h"
#include "timer.h"
#include "rgb_matrix_user.h"
#include "my_keymap.h"
#ifdef VIM_MOTIONS
#	include "vim_motions.h"
#endif
#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif
// ============================================================================
// KEYBOARD POST-INITIALIZATION
// ============================================================================
// Set the custom circuit effect as the default RGB matrix effect
// This runs once when the keyboard initializes
// ============================================================================

void keyboard_post_init_user(void) {
    // Set the custom circuit effect as default
    rgb_matrix_mode(RGB_MATRIX_CUSTOM_circuit_complete_effect);
	//split_transport_register_rpc(sizeof(rgb_sync), (void *)&rgb_sync);
    // Optional: Configure RGB matrix settings for optimal circuit effect performance
    rgb_matrix_sethsv(255, 255, 128); // Max brightness and saturation
}

// ============================================================================
// AUDIO CONFIGURATION
// ============================================================================

#ifdef AUDIO_ENABLE
float tone_enter[][2] = SONG(GOODBYE_SOUND);
float tone_fail[][2]  = SONG(MUSIC_OFF_SOUND);
float tone_exit[][2]  = SONG(MUSIC_ON_SOUND);
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define MY_SYM LT(_SYM, KC_NO)
#define MY_NAV LT(_NAV, KC_NO)
#define MY_NVSY LT(_NVSY, KC_NO)
#define MY_SHFT MT(MOD_LSFT, KC_CAPS)

enum layers {
    _BASE,
    _SYM,
    _NAV,
    _NVSY,
    _SYST,
};



#ifdef VIM_MOTIONS
enum {
	TD_VI_Y,
};

tap_dance_action_t tap_dance_actions[] = {
	[TD_VI_Y] = ACTION_TAP_DANCE_FN(tap_dance_VI_Y),
};
#endif

layer_state_t layer_state_set_user(layer_state_t state) {
    if (layer_state_cmp(state, _SYM)) {
        if (!host_keyboard_led_state().num_lock) {
            tap_code(KC_NUM);
        }
    }
    return state;
}

const uint16_t PROGMEM sym_space_combo[] = {MY_SYM, KC_SPC, COMBO_END};
const uint16_t PROGMEM nav_space_combo[] = {MY_NAV, KC_SPC, COMBO_END};
const uint16_t PROGMEM shift_sym_combo[] = {MY_SHFT, MY_SYM, COMBO_END};
combo_t key_combos[] = {
    COMBO(sym_space_combo, KC_UNDS),
    COMBO(nav_space_combo, KC_TAB),
	COMBO(shift_sym_combo, KC_0),	//I don't like this. Better off without it.
};

const key_override_t shift_0 = ko_make_basic(MOD_MASK_SHIFT, KC_0, KC_KP_0);
const key_override_t shift_1 = ko_make_basic(MOD_MASK_SHIFT, KC_1, KC_KP_1);
const key_override_t shift_2 = ko_make_basic(MOD_MASK_SHIFT, KC_2, KC_KP_2);
const key_override_t shift_3 = ko_make_basic(MOD_MASK_SHIFT, KC_3, KC_KP_3);
const key_override_t shift_4 = ko_make_basic(MOD_MASK_SHIFT, KC_4, KC_KP_4);
const key_override_t shift_5 = ko_make_basic(MOD_MASK_SHIFT, KC_5, KC_KP_5);
const key_override_t shift_6 = ko_make_basic(MOD_MASK_SHIFT, KC_6, KC_KP_6);
const key_override_t shift_7 = ko_make_basic(MOD_MASK_SHIFT, KC_7, KC_KP_7);
const key_override_t shift_8 = ko_make_basic(MOD_MASK_SHIFT, KC_8, KC_KP_8);
const key_override_t shift_9 = ko_make_basic(MOD_MASK_SHIFT, KC_9, KC_KP_9);

const key_override_t shift_bspc = ko_make_basic(MOD_MASK_SHIFT, KC_BSPC, KC_DEL);
const key_override_t tilde_override = ko_make_basic(MOD_MASK_SHIFT, S(KC_GRV), KC_GRV);   // Shift+GRV -> GRV
const key_override_t pipe_override = ko_make_basic(MOD_MASK_SHIFT, S(KC_BSLS), KC_BSLS); // Shift+BSLS -> BSLS

const key_override_t *key_overrides[] = {&shift_0, &shift_1, &shift_2, &shift_3, &shift_4, &shift_5, &shift_6, &shift_7, &shift_8, &shift_9, &shift_bspc,
	&tilde_override, &pipe_override, NULL};

static layer_state_t saved_layer_state;
static bool          is_active         = false;
static bool          other_key_pressed = false;
static uint16_t      press_timer;
static keypos_t      reset_key_pos;

static uint16_t copy_timer;
key_release_mask_t key_release_mask;
//uint16_t my_td_timer; not needed if I use the builtin tap dance.
//VIM Variables
// static bool replace_char = false;
// static bool replace_cont = false;
// static bool cmd_change = false;

uint8_t saved_mods;
uint8_t saved_weak_mods;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
	uint8_t led = g_led_config.matrix_co[record->event.key.row][record->event.key.col];
	if (led != NO_LED){
		//use the actual pressed masks of the individual circuit structs.
		if (record->event.pressed){
			send_circuit_led(led, true);//pressed_mask |= (1ULL << led);
		} else {
			send_circuit_led(led, false);//pressed_mask |= (1ULL << led);
		}
	}

    // Detect other keys while the reset key is physically held
    if (is_active && !(record->event.key.row == reset_key_pos.row && record->event.key.col == reset_key_pos.col) &&
        record->event.pressed) {
        if (!other_key_pressed) {
            other_key_pressed = true;
            layer_clear();
        }
    }
	
	saved_mods = get_mods();
	//saved_weak_mods = get_weak_mods();

    switch (keycode) {
        case MY_BASE: 
            if (record->event.pressed) {
                saved_layer_state = layer_state;
                reset_key_pos     = record->event.key;
                is_active         = true;
                other_key_pressed = false;
                press_timer       = timer_read();
            }
            return false;

		case MY_SYM: 
			if (record->tap.count && record->event.pressed) {
					layer_invert(_SYM);
					return false;
				}							
            return true;

        case MY_NAV: 
            if (record->tap.count && record->event.pressed) {
                layer_invert(_NAV);
                return false;
            }
            return true;

        case MY_NVSY: 
            if (record->tap.count && record->event.pressed) {
                layer_off(_NAV);
                layer_on(_SYM);
                return false;
            }
            return true;

        case MY_COPY:
            if (record->event.pressed) {
                copy_timer = timer_read();
            } else {
                if (timer_elapsed(copy_timer) < TAPPING_TERM) {
                    tap_code16(LCTL(KC_C));
                } else {
                    tap_code16(LCTL(LSFT(KC_C)));
                }
            }
            return false;

        case MY_CUT:
            if (record->event.pressed) {
                copy_timer = timer_read();
            } else {
                if (timer_elapsed(copy_timer) < TAPPING_TERM) {
                    tap_code16(LCTL(KC_X));
                } else {
                    tap_code16(LCTL(LSFT(KC_X)));
                }
            }
            return false;

        case MY_PASTE:
            if (record->event.pressed) {
                copy_timer = timer_read();
            } else {
                if (timer_elapsed(copy_timer) < TAPPING_TERM) {
                    tap_code16(LCTL(KC_V));
                } else {
                    tap_code16(LCTL(LSFT(KC_V)));
                }
            }
            return false;
		
#ifdef VIM_MOTIONS
		case VI_W:
		return w_vim_key(record->event.pressed);

		case VI_R:
		return r_vim_key(record->event.pressed);
			
		case VI_U:
		return u_vim_key(record->event.pressed);

		case VI_O:
		return o_vim_key(record->event.pressed);

		case VI_P:
		return p_vim_key(record->event.pressed);	

			
#endif
   case MY_SYST:
            if (record->event.pressed) {
                if ((saved_mods & MOD_MASK_CTRL) && (saved_mods & MOD_MASK_ALT)) {
                    if (!layer_state_is(_SYST)) {
                        layer_on(_SYST);
#ifdef AUDIO_ENABLE
                        PLAY_SONG(tone_enter);
#endif
                    } else {
                        layer_off(_SYST);
#ifdef AUDIO_ENABLE
                        PLAY_SONG(tone_exit);
#endif
                    }
                } else {
#ifdef AUDIO_ENABLE
                    PLAY_SONG(tone_fail);
#endif
                }
                return false;
            }
            return true;
    }
    return true;
}

void matrix_scan_user(void) {
    if (is_active) {
        if (!matrix_is_on(reset_key_pos.row, reset_key_pos.col)) {
            // Physical release detected
            is_active = false;

            if (!other_key_pressed && timer_elapsed(press_timer) < TAPPING_TERM) {
                // TAP
                layer_clear();
            } else if (other_key_pressed) {
                // MOD USE
                layer_state = saved_layer_state;
            }
        }
    }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[_BASE] = LAYOUT_split_3x6_3(
    // |........|........|........|........|........|........|........|........|........|........|........|........|........|........|
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,             KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC,
		KC_ESC,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,             KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
		MY_NAV,  KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,  		   KC_N, 	KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
								   KC_LCTL, KC_LGUI, MY_SHFT,		   KC_SPC, MY_SYM, KC_LALT),
    //    [_SYM] = LAYOUT_split_3x6_3(
    // |........|........|........|........|........|........|........|........|........|........|........|........|........|........|
    //  _______, KC_LCBR, KC_LBRC, KC_LPRN, KC_PIPE, KC_PERC,          KC_CIRC, KC_AMPR, KC_RPRN, KC_RBRC, KC_RCBR, _______, 
	//	MY_BASE, KC_1,    KC_2,    KC_3,    KC_4,    KC_5, 			   KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    _______, 
	//	_______, KC_ASTR, KC_HASH, KC_DLR,  KC_PLUS, KC_EXLM, 		   KC_EQL,  KC_MINS, _______, _______, _______, _______, 
	//								_______, _______, _______,          _______, _______, _______),
        [_SYM] = LAYOUT_split_3x6_3(
    // |........|........|........|........|........|........|........|........|........|........|........|........|........|........|
        _______, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,          KC_AMPR, KC_7,    KC_8,    KC_9,   S(KC_GRV), _______, //maybe make GRV a new keycode with tilde as default, shift = KC_GRV
	  	MY_BASE, KC_LCBR, KC_LPRN, KC_RPRN, KC_RCBR,S(KC_BSLS),	  	   KC_SLSH, KC_4,    KC_5,    KC_6,    KC_MINS, KC_EQL,  //maybe make BSLS have PIPE as default
	  	_______, KC_LABK, KC_LBRC, KC_RBRC, KC_RABK, KC_CIRC, 		   KC_ASTR, KC_1,    KC_2,    KC_3,    KC_PLUS, _______, 
	  								_______, _______, _______,         _______, KC_0, _______),

    //  [_SYM] = LAYOUT_split_3x6_3(
    // |........|........|........|........|........|........|........|........|........|........|........|........|........|........|
    //  _______, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,          KC_AMPR, KC_CIRC, KC_ASTR, KC_MINS, KC_PLUS, _______, 
	//	MY_BASE, KC_1, 	  KC_2,    KC_3,    KC_4,    KC_5,   		   KC_6,    KC_7,    KC_8,    KC_9,    KC_0,   S(KC_GRV), 	   
	//	_______, KC_LCBR, KC_LPRN, KC_RPRN, KC_RCBR, S(KC_BSLS), 	   KC_RCBR, KC_LPRN, KC_LABK, KC_RABK, KC_SLSH, _______, 
	//								_______, _______, KC_EQL,         _______, _______, _______),
#if defined(BASIC_BANKARU)
        [_NAV] = LAYOUT_split_3x6_3(
     //|........|........|........|........|........|........|........|........|........|........|........|........|........|........|
        _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   		   KC_F11,  KC_F12,  KC_UP,   KC_GRV,  KC_PAUS, _______,
		MY_BASE, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10, 		   KC_INS,  KC_LEFT, KC_DOWN, KC_RGHT, KC_SCRL, KC_PSCR, 
		_______, KC_AT,   MY_CUT,  MY_COPY, MY_PASTE, KC_NUM, 		   KC_LSCR, KC_BSLS, KC_TILD, KC_MENU, MY_SYST, _______,
		                           _______, _______, _______, 		   _______, MY_NVSY, _______),
#elif defined(VIM_MOTIONS) 
        [_NAV] = LAYOUT_split_3x6_3(				//can't do find or till...
     //|........|........|........|........|........|........|........|........|........|........|........|........|........|........|
        _______, KC_F1,   VI_W,  VI_E,    VI_R,    KC_F5,   	   TD(TD_VI_Y), VI_U,    KC_UP,   VI_O,    VI_P,    _______,
		MY_BASE, VI_A,    VI_S,    VI_D,    KC_F9,   KC_F10, 		   KC_INS,  KC_LEFT, KC_DOWN, KC_RGHT, KC_SCRL, MY_SYST, 
		_______, _______,   VI_X,    VI_C, 	VI_V,	 VI_B, 			   _______, _______, _______, _______, _______, _______,
		                           _______, _______, _______, 		   _______, MY_NVSY, _______),
#else
#error "You must define either BASIC_BANKARU or VIM_MOTIONS in config.h"
#endif
        [_NVSY] = LAYOUT_split_3x6_3(
    // |........|........|........|........|........|........|........|........|........|........|........|........|........|........|
        _______, _______, _______, _______, _______, _______, 		   _______, _______, _______, KC_PGUP, _______, _______,
		MY_BASE, _______, _______, _______, XXXXXXX, _______,          _______, _______, KC_HOME, KC_PGDN, KC_END,  _______,
		KC_END, _______, _______, _______, _______, _______,           _______, _______, _______, _______, _______, _______,
	                              _______, _______, _______,           _______, _______, _______),
        [_SYST] = LAYOUT_split_3x6_3(
    // |........|........|........|........|........|........|........|........|........|........|........|........|........|........|
        QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, QK_MAKE,          DB_TOGG, QK_RBT,  XXXXXXX, XXXXXXX, XXXXXXX, _______, 
		MY_BASE, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,          EE_CLR,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		RM_VALU, RM_HUEU, RM_SATU, RM_NEXT, RM_TOGG, XXXXXXX,          RM_VALD, RM_HUED, RM_SATD, RM_PREV, CK_TOGG, _______,
							       _______, _______, MY_BASE,          _______, _______, _______)};
static void set_conn_bit(circuit *cir, uint8_t column, bool on){
	if (on){
		cir->active_led_mask |= column;
	} else {
		cir->active_led_mask &= ~column;
	}
}

void send_circuit_led(uint8_t led, bool on) {
	switch (led) {
//BACK LIGHTS
		case LED_BACK_0:  {//0
			 break;
		 }
		case LED_BACK_1: {//1
			break;
		}
		case LED_BACK_2:{//2
		   break;
			   }
		case LED_BACK_3: {//3
			break;
				}
		case LED_BACK_4: {//4
					break;
				}
		case LED_BACK_5: {//5
					break;
				}
		case LED_BACK_6: {//27
					//if caps lock is on turn it on
					break;
				}
		case LED_BACK_7: {//28
					break;
				}
		case LED_BACK_8: {//29
					break;
			 }
		case LED_BACK_9: {//30
					break;
			 }
		case LED_BACK_10: {//31
					break;
			 }
		case LED_BACK_11: {//32
					break;
			 }
//LEFT HALF
		case LED_L_0_OUTER: {//24
					set_conn_bit(&circuits[LEFT_TOP_CIR], COL_MASK_OUTER, on);
					break;
			 }
		case LED_L_0_PINKY: {//23
					set_conn_bit(&circuits[LEFT_TOP_CIR], COL_MASK_PINKY, on);
					break;
			 }
		case LED_L_0_RING: {//18
					set_conn_bit(&circuits[LEFT_TOP_CIR], COL_MASK_RING, on);
					break;
			 }
		case LED_L_0_MID: {//17
					set_conn_bit(&circuits[LEFT_TOP_CIR], COL_MASK_MID, on);
					break;
			 }
		case LED_L_0_INDEX: {//10
				set_conn_bit(&circuits[LEFT_TOP_CIR], COL_MASK_INDEX, on);
					break;
			}
		case LED_L_0_INNER: {//9
				set_conn_bit(&circuits[LEFT_TOP_CIR], COL_MASK_INNER, on);
					break;
		}
		case LED_L_1_OUTER: {//25
					set_conn_bit(&circuits[LEFT_MID_CIR], COL_MASK_OUTER, on);
					break;
			 }
		case LED_L_1_PINKY: {//22
					set_conn_bit(&circuits[LEFT_MID_CIR], COL_MASK_PINKY, on);
					break;
			 }
		case LED_L_1_RING: {//19
					set_conn_bit(&circuits[LEFT_MID_CIR], COL_MASK_RING, on);
					break;
			 }
		case LED_L_1_MID: {//16
					set_conn_bit(&circuits[LEFT_MID_CIR], COL_MASK_MID, on);
					break;
			 }
		case LED_L_1_INDEX: {//11
				set_conn_bit(&circuits[LEFT_MID_CIR], COL_MASK_INDEX, on);
					break;
			}
		case LED_L_1_INNER: {//8
				set_conn_bit(&circuits[LEFT_MID_CIR], COL_MASK_INNER, on);
					break;
		}
		case LED_L_2_OUTER: {//26
					set_conn_bit(&circuits[LEFT_BTM_CIR], COL_MASK_OUTER, on);
					break;
			 }
		case LED_L_2_PINKY: {//21
					set_conn_bit(&circuits[LEFT_BTM_CIR], COL_MASK_PINKY, on);
					break;
			 }
		case LED_L_2_RING: {//20
					set_conn_bit(&circuits[LEFT_BTM_CIR], COL_MASK_RING, on);
					break;
			 }
		case LED_L_2_MID: {//15
					set_conn_bit(&circuits[LEFT_BTM_CIR], COL_MASK_MID, on);
					break;
			 }
		case LED_L_2_INDEX: {//12
				set_conn_bit(&circuits[LEFT_BTM_CIR], COL_MASK_INDEX, on);
					break;
			}
		case LED_L_2_INNER: {//7
				set_conn_bit(&circuits[LEFT_BTM_CIR], COL_MASK_INNER, on);
					break;
		}
//RIGHT HALF	
		case LED_R_0_OUTER: {//51
					set_conn_bit(&circuits[RIGHT_TOP_CIR], COL_MASK_OUTER, on);
					break;
			 }
		case LED_R_0_PINKY: {//50
					set_conn_bit(&circuits[RIGHT_TOP_CIR], COL_MASK_PINKY, on);
					break;
			 }
		case LED_R_0_RING: {//45
					set_conn_bit(&circuits[RIGHT_TOP_CIR], COL_MASK_RING, on);
					break;
			 }
		case LED_R_0_MID: {//44
					set_conn_bit(&circuits[RIGHT_TOP_CIR], COL_MASK_MID, on);
					break;
			 }
		case LED_R_0_INDEX: {//37
				set_conn_bit(&circuits[RIGHT_TOP_CIR], COL_MASK_INDEX, on);
					break;
			}
		case LED_R_0_INNER: {//36
				set_conn_bit(&circuits[RIGHT_TOP_CIR], COL_MASK_INNER, on);
					break;
		}
		case LED_R_1_OUTER: {//52
					set_conn_bit(&circuits[RIGHT_MID_CIR], COL_MASK_OUTER, on);
					break;
			 }
		case LED_R_1_PINKY: {//49
					set_conn_bit(&circuits[RIGHT_MID_CIR], COL_MASK_PINKY, on);
					break;
			 }
		case LED_R_1_RING: {//46
					set_conn_bit(&circuits[RIGHT_MID_CIR], COL_MASK_RING, on);
					break;
			 }
		case LED_R_1_MID: {//43
					set_conn_bit(&circuits[RIGHT_MID_CIR], COL_MASK_MID, on);
					break;
			 }
		case LED_R_1_INDEX: {//38
				set_conn_bit(&circuits[RIGHT_MID_CIR], COL_MASK_INDEX, on);
					break;
			}
		case LED_R_1_INNER: {//35
				set_conn_bit(&circuits[RIGHT_MID_CIR], COL_MASK_INNER, on);
					break;
		}
		case LED_R_2_OUTER: {//53
					set_conn_bit(&circuits[RIGHT_BTM_CIR], COL_MASK_OUTER, on);
					break;
			 }
		case LED_R_2_PINKY: {//48
					set_conn_bit(&circuits[RIGHT_BTM_CIR], COL_MASK_PINKY, on);
					break;
			 }
		case LED_R_2_RING: {//47
					set_conn_bit(&circuits[RIGHT_BTM_CIR], COL_MASK_RING, on);
					break;
			 }
		case LED_R_2_MID: {//42
					set_conn_bit(&circuits[RIGHT_BTM_CIR], COL_MASK_MID, on);
					break;
			 }
		case LED_R_2_INDEX: {//39
				set_conn_bit(&circuits[RIGHT_BTM_CIR], COL_MASK_INDEX, on);
					break;
			}
		case LED_R_2_INNER: {//34
				set_conn_bit(&circuits[RIGHT_BTM_CIR], COL_MASK_INNER, on);
					break;
		}
//THUMB KEYS
		case LED_L_3_THUMB_OUTER: {//14
				//circuit_eff_leds[led] = on;
				if (on){
				thumb_key_mask |= THUMB_MASK_L_OUTER;
				} else {
				thumb_key_mask &= ~THUMB_MASK_L_OUTER;
				}
				break;
			 }
		case LED_L_3_THUMB_MID: {//13
				//circuit_eff_leds[led] = on;
				if (on) {
					thumb_key_mask |= THUMB_MASK_L_MID;
				} else {
					thumb_key_mask &= ~THUMB_MASK_L_MID;
				}
				break;	
			 }
		case LED_L_3_THUMB_INNER: {//6
				//circuit_eff_leds[led] = on;
				if (on) {
					thumb_key_mask |= THUMB_MASK_L_INNER;
				} else {
					thumb_key_mask &= ~THUMB_MASK_L_INNER;
				}
				break;	
			 }
		case LED_R_3_THUMB_INNER: {//33
				//circuit_eff_leds[led] = on;
				if (on) {
					thumb_key_mask |= THUMB_MASK_R_OUTER;
				} else {
					thumb_key_mask &= ~THUMB_MASK_R_OUTER;
				}
				break;
			 }
		case LED_R_3_THUMB_MID: {//40
				//circuit_eff_leds[led] = on;
				if (on) {
					thumb_key_mask |= THUMB_MASK_R_MID;
				} else {
					thumb_key_mask &= ~THUMB_MASK_R_MID;
				}
				break;
			}
		case LED_R_3_THUMB_OUTER: {//41
				//circuit_eff_leds[led] = on;
				if (on) {
					thumb_key_mask |= THUMB_MASK_R_OUTER;
				} else {
					thumb_key_mask &= ~THUMB_MASK_R_OUTER;
				}
				break;
			}
	}
}

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
